SET PATH=C:\"Documents and Settings"\"All Users"\Documents\e\MASM611\BIN;C:\"Documents and Settings"\"All Users"\Documents\e\MASM611\BINR;%PATH%
SET LIB=C:\"Documents and Settings"\"All Users"\Documents\e\MASM611\LIB
SET INCLUDE=C:\"Documents and Settings"\"All Users"\Documents\e\MASM611\INCLUDE
SET INIT=C:\"Documents and Settings"\"All Users"\Documents\e\MASM611\INIT
SET HELPFILES=C:\"Documents and Settings"\"All Users"\Documents\e\MASM611\HELP\*.HLP
SET ASMEX=C:\"Documents and Settings"\"All Users"\Documents\e\MASM611\SAMPLES
SET TMP=C:\WINDOWS\TEMP
rem mouse.com
C:\"Documents and Settings"\"All Users"\Documents\e\MASM611\BINR\pwb